# Generated by Django 4.2.6 on 2023-10-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_userlike_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
